import type { DiagnosticSeverity } from "./ast.js";

export const DIAGNOSTIC_CODES = {
  FRONTMATTER_INVALID: "NABLA_FRONTMATTER_INVALID",
  LINK_MISSING_TARGET: "NABLA_LINK_MISSING_TARGET",
  LINK_AMBIGUOUS_TARGET: "NABLA_LINK_AMBIGUOUS_TARGET",
  WIKI_LINK_INVALID_TARGET: "NABLA_WIKI_LINK_INVALID_TARGET",
  HEADING_MISSING_TARGET: "NABLA_HEADING_MISSING_TARGET",
  BLOCK_MISSING_TARGET: "NABLA_BLOCK_MISSING_TARGET",
  BLOCK_ID_INVALID: "NABLA_BLOCK_ID_INVALID",
  BLOCK_ID_INVALID_POSITION: "NABLA_BLOCK_ID_INVALID_POSITION",
  BLOCK_ID_DUPLICATE: "NABLA_BLOCK_ID_DUPLICATE",
  TOOLTIP_EMPTY_TARGET: "NABLA_TOOLTIP_EMPTY_TARGET",
  TOOLTIP_UNCLOSED: "NABLA_TOOLTIP_UNCLOSED",
  HIGHLIGHT_UNCLOSED: "NABLA_HIGHLIGHT_UNCLOSED",
  HIGHLIGHT_INVALID_COLOR: "NABLA_HIGHLIGHT_INVALID_COLOR",
  CALLOUT_INVALID_TYPE: "NABLA_CALLOUT_INVALID_TYPE",
  TOGGLE_MISSING_TITLE: "NABLA_TOGGLE_MISSING_TITLE",
  TRANSCLUSION_INLINE_UNSUPPORTED: "NABLA_TRANSCLUSION_INLINE_UNSUPPORTED",
  TRANSCLUSION_MISSING_TARGET: "NABLA_TRANSCLUSION_MISSING_TARGET",
  TRANSCLUSION_CYCLE: "NABLA_TRANSCLUSION_CYCLE",
  TRANSCLUSION_DEPTH_LIMIT: "NABLA_TRANSCLUSION_DEPTH_LIMIT",
  EMOJI_UNKNOWN: "NABLA_EMOJI_UNKNOWN",
  FOOTNOTE_MISSING_DEFINITION: "NABLA_FOOTNOTE_MISSING_DEFINITION",
  FOOTNOTE_UNUSED_DEFINITION: "NABLA_FOOTNOTE_UNUSED_DEFINITION",
  EDITOR_EXPORT_LOSS: "NABLA_EDITOR_EXPORT_LOSS"
} as const;

export type DiagnosticCode =
  (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];

export type DiagnosticCatalogEntry = {
  code: DiagnosticCode;
  severity: DiagnosticSeverity;
};

export const DIAGNOSTIC_CATALOG = [
  { code: DIAGNOSTIC_CODES.FRONTMATTER_INVALID, severity: "warning" },
  { code: DIAGNOSTIC_CODES.LINK_MISSING_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.LINK_AMBIGUOUS_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.WIKI_LINK_INVALID_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.HEADING_MISSING_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.BLOCK_MISSING_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.BLOCK_ID_INVALID, severity: "warning" },
  { code: DIAGNOSTIC_CODES.BLOCK_ID_INVALID_POSITION, severity: "warning" },
  { code: DIAGNOSTIC_CODES.BLOCK_ID_DUPLICATE, severity: "warning" },
  { code: DIAGNOSTIC_CODES.TOOLTIP_EMPTY_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.TOOLTIP_UNCLOSED, severity: "warning" },
  { code: DIAGNOSTIC_CODES.HIGHLIGHT_UNCLOSED, severity: "warning" },
  { code: DIAGNOSTIC_CODES.HIGHLIGHT_INVALID_COLOR, severity: "warning" },
  { code: DIAGNOSTIC_CODES.CALLOUT_INVALID_TYPE, severity: "warning" },
  { code: DIAGNOSTIC_CODES.TOGGLE_MISSING_TITLE, severity: "info" },
  {
    code: DIAGNOSTIC_CODES.TRANSCLUSION_INLINE_UNSUPPORTED,
    severity: "warning"
  },
  { code: DIAGNOSTIC_CODES.TRANSCLUSION_MISSING_TARGET, severity: "warning" },
  { code: DIAGNOSTIC_CODES.TRANSCLUSION_CYCLE, severity: "error" },
  { code: DIAGNOSTIC_CODES.TRANSCLUSION_DEPTH_LIMIT, severity: "warning" },
  { code: DIAGNOSTIC_CODES.EMOJI_UNKNOWN, severity: "info" },
  { code: DIAGNOSTIC_CODES.FOOTNOTE_MISSING_DEFINITION, severity: "warning" },
  { code: DIAGNOSTIC_CODES.FOOTNOTE_UNUSED_DEFINITION, severity: "info" },
  { code: DIAGNOSTIC_CODES.EDITOR_EXPORT_LOSS, severity: "error" }
] as const satisfies readonly DiagnosticCatalogEntry[];

export type DiagnosticCatalog = typeof DIAGNOSTIC_CATALOG;
